### ISSUE TITLE
could not find file 

### ISSUE THREAD

**Issue by meiyongsheng** [johnno1962/injectionforxcode#253]
*** Compiling /Users/mys/Desktop/***/GiftedStudent1/TKApp/modules/finances/Controller/TFSFinancesRootViewController.m ***
*** Re-compilation failed (/Users/mys/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/mys/Desktop/***/GiftedStudent1/TKApp/Modules/sso/Model/TFSFundAccountInfo.h' referenced by AST file '/Users/mys/Library/Developer/Xcode/DerivedData/Build/Intermediates.noindex/PrecompiledHeaders/GCS-Prefix-cqmfxvynofpsafafwdhhlfljpkor/GCS-Prefix.pch.pch''
note: after modifying system headers, please delete the module cache at '/Users/mys/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/1CC1MBM3VFV58'
1 error generated.

**Comment by johnno1962** [comment]
This can be to do with the fact injected uses a case sensitive file system.

**Comment by iceYou123** [comment]
+1 help

**Comment by aiewing** [comment]
I also had this problem

**Comment by johnno1962** [comment]
What version are you using? Is this InjectionIII? Can you download one of the non-sandboxed releases from https://github.com/johnno1962/InjectionIII/releases and you can eliminate case sensitivity problems.

**Comment by aiewing** [comment]
> What version are you using? Is this InjectionIII? Can you download one of the non-sandboxed releases from https://github.com/johnno1962/InjectionIII/releases and you can eliminate case sensitivity problems.

I tried "2.7.0 for Big Sur & Apple Silicon with integrated unhide" just now. But InjectionIII cant connect to project.

**Comment by johnno1962** [comment]
I'll need to know a lot more about your project to be able to help. Are you able to TeamView or Google Hangout?

**Comment by aiewing** [comment]
> I'll need to know a lot more about your project to be able to help. Are you able to TeamView or Google Hangout?

I download it from the Appstore(v2.6.3), run it and commond + S. (I dont add "-Xlinker -interposable", because it will cause an error)
💉 *** Compiling /Users/aiewing/QKGit/FlagiOS/FLAG/Me/Fans/MeFanVC.m ***
💉 *** Re-compilation failed (see: /var/folders/p8/3ysnw7ln1q71k26rxxfflh140000gn/T/com.johnholdsworth.InjectionIII/command.sh)
fatal error: malformed or corrupted AST file: 'could not find file '/Users/aiewing/QKGit/FlagiOS/FlAG/flag-prefiex.pch' referenced by AST file '/Users/aiewing/Library/Developer/Xcode/DerivedData/FLAG-ggjctuchlposkugvjofgeahzrgdz/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/15835372413573028407/flag-prefiex.pch.gch''
note: after modifying system headers, please delete the module cache at '/Users/aiewing/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/X14N2TCTAXZP'
1 error generated.

**Comment by aiewing** [comment]
My project is mix of OC and swift, and mainly is Swift. appDelegate is swift.

**Comment by johnno1962** [comment]
ObjectC + Swift + InjectionIII is not a good mix. The problem is intermediate files created by swift are deleted and not available when it come to injecting. It works for some people but you may not be able to use injection on your particular project. Without being able to see your project I can't say much more

**Comment by aiewing** [comment]
> I'll need to know a lot more about your project to be able to help. Are you able to TeamView or Google Hangout?

I'll import the project to my computer later and contact you again. The company computer can't install these.
