### ISSUE TITLE
It can not work

### ISSUE THREAD

**Issue by lanht** [johnno1962/injectionforxcode#291]
xxx.m is not readable. This could be because
the file is in a secure area of the file system or because the
case of the letters in the file name does not match that in the
Xcode project. The file system injection uses is case sensitive

**Comment by zenangst** [comment]
@lanht hey mate, mind sharing some more details about your setup?

**Comment by lanht** [comment]
[[NSBundle bundleWithPath:@"/Applications/InjectionIII.app/Contents/Resources/iOSInjection.bundle"] load];

**Comment by zenangst** [comment]
What kind of class are you trying to inject? Does it have a `injected` method implemented so that `InjectionIII` knows that it is valid to inject, and if so… what does that method look like?

In addition to that, whee do you have your files stored? The application is sandboxed a thus it is restricted from reading files in certain locations.
